"""Manuscript figure — a panel of 6 example recordings (focal / generalized slowing of varying degree, in
different sleep stages) with (a) our BRIEF finding line, (b) our FULL report paragraph, and (c) the clinical
report for comparison — shown as its STRUCTURED descriptors (raw report text is PHI and is never rendered).

Each card also shows a compact regional delta-excess deviation strip (6 regions) that visually distinguishes
focal (one region high) from diffuse (all elevated). Reports are generated by the SAME governed generator
used in §4 D6 (scripts/58). Reuses description_recording/description_stage + recording_labels(_sap) +
recording_meta (age/sex).

Run: PYTHONPATH=src MPLBACKEND=Agg python3 scripts/62_example_reports_panel.py
Writes figures/story/s4_examples_panel.png + results/story/s4_examples.md
"""
from __future__ import annotations
import importlib.util, textwrap
from pathlib import Path
import numpy as np, pandas as pd
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch

m58 = importlib.util.module_from_spec(importlib.util.spec_from_file_location("m58", "scripts/58_description_words.py"))
importlib.util.spec_from_file_location("m58", "scripts/58_description_words.py").loader.exec_module(m58)

FIG = Path("figures/story"); RES = Path("results/story")
REGN = ["reg_anterior", "reg_L_temporal", "reg_R_temporal", "reg_L_parasagittal", "reg_R_parasagittal", "reg_posterior"]
REGL = ["ant", "L-temp", "R-temp", "L-para", "R-para", "post"]
STAGES = ["W", "N1", "N2", "N3", "REM"]


def report_structured(r):
    """PHI-free stand-in for the clinical report: its structured finding labels."""
    parts = []
    if bool(getattr(r, "slowing_focal", False)):
        loc = " ".join(x for x in [str(getattr(r, "focal_side", "") or ""), str(getattr(r, "focal_region", "") or "")] if x and x != "nan")
        b = str(getattr(r, "focal_band", "") or ""); b = "" if b == "nan" else b
        parts.append("focal slowing" + (f", {loc}" if loc.strip() else "") + (f" ({b})" if b else ""))
    if bool(getattr(r, "slowing_gen_pathologic", False)):
        topo = str(getattr(r, "gen_topography", "") or ""); topo = "" if topo in ("nan", "unspec") else topo
        b = str(getattr(r, "gen_band", "") or ""); b = "" if b == "nan" else b
        parts.append("generalized slowing" + (f", {topo}" if topo else "") + (f" ({b})" if b else ""))
    return "; ".join(parts) if parts else "slowing (unspecified)"


def main():
    FIG.mkdir(parents=True, exist_ok=True); RES.mkdir(parents=True, exist_ok=True)
    R = pd.read_parquet("data/derived/description_recording.parquet")
    S = pd.read_parquet("data/derived/description_stage.parquet")
    lab = pd.read_parquet("data/derived/recording_labels.parquet").drop_duplicates("eeg_id")
    sap = pd.read_parquet("data/derived/recording_labels_sap.parquet").drop_duplicates("eeg_id")
    meta = pd.read_parquet("data/derived/recording_meta.parquet").drop_duplicates("eeg_id").set_index("eeg_id")
    d = R.merge(lab[["eeg_id", "focal_side", "focal_region", "focal_band", "gen_band", "gen_topography"]], on="eeg_id") \
         .merge(sap[["eeg_id", "slowing_focal", "slowing_gen_pathologic"]], on="eeg_id")
    d = d[d.slowing_focal.fillna(False) | d.slowing_gen_pathologic.fillna(False)].copy()
    S = S[S.eeg_id.isin(set(d.eeg_id))].copy(); S["amount"] = S[["delta_p90", "theta_p90"]].max(axis=1)
    stage_map = {eid: {r.stage: (r.prevalence, r.n_seg, r.amount) for r in g.itertuples()} for eid, g in S.groupby("eeg_id")}
    d["isfoc"] = d.apply(m58.ourisfoc, axis=1)
    d["peakz"] = [m58.magnitude(r, r.isfoc) for r in d.itertuples()]
    d["domstage"] = d.eeg_id.map(lambda e: max(stage_map.get(e, {"W": (0, 0, -9)}), key=lambda s: stage_map[e][s][2]) if stage_map.get(e) else "W")
    d["age"] = d.eeg_id.map(meta.age); d["sex"] = d.eeg_id.map(meta.sex)
    d["our_side"] = [m58.our_side(v) for v in d.lat_signed]
    d["concord"] = (d.our_side == d.focal_side) | (d.focal_side.isna())            # side agrees (or n/a for gen)
    d = d[d.peakz.notna() & d.age.notna() & (d.n_seg >= 20)]

    # --- pick 6 CONCORDANT examples (our field agrees slowing is present), 3 focal + 3 generalized,
    #     spanning degree (marked/moderate/mild) and DIFFERENT dominant sleep stages ---
    def pick(pool, used_ids, used_stages, band):
        lo, hi = band
        p = pool[(pool.peakz >= lo) & (pool.peakz < hi) & (~pool.eeg_id.isin(used_ids))]
        if not len(p):                                                                # relax band if empty
            p = pool[(pool.peakz >= 1.0) & (~pool.eeg_id.isin(used_ids))]
        if not len(p):
            return None
        pu = p[~p.domstage.isin(used_stages)]                                          # prefer an unused stage
        p = pu if len(pu) else p
        pc = p[p.concord]                                                              # prefer report-concordant side
        p = pc if len(pc) else p
        return p.sort_values("n_seg", ascending=False).iloc[0]
    foc = d[d.isfoc & (d.slowing_focal == True) & d.focal_side.notna()]              # noqa: E712
    gen = d[(~d.isfoc) & (d.slowing_gen_pathologic == True)]                          # noqa: E712
    MARKED, MODERATE, MILD = (3.0, 12.0), (1.8, 3.0), (1.0, 1.8)
    used_ids, used_stages, chosen = set(), [], []
    for pool, band in [(foc, MARKED), (foc, MODERATE), (foc, MILD),
                       (gen, MARKED), (gen, MODERATE), (gen, MILD)]:
        r = pick(pool, used_ids, used_stages, band)
        if r is not None:
            used_ids.add(r.eeg_id); used_stages.append(r.domstage); chosen.append(r)
    ex = pd.DataFrame(chosen).reset_index(drop=True)

    # --- render 6 cards (one row each) ---
    n = len(ex); fig = plt.figure(figsize=(12.5, 3.0 * n + 0.5))
    gs = fig.add_gridspec(n, 2, width_ratios=[1, 4.0], hspace=0.55, wspace=0.06)
    md = ["# Example generated reports vs the clinical report (6 recordings)\n",
          "Our BRIEF finding line and FULL report paragraph (governed by docs/claims_table.md — magnitude in "
          "SD/centile, no severity adjective) beside the clinical report's STRUCTURED descriptors (raw report "
          "text withheld as PHI). Regional strip = per-region delta-excess deviation z (focal = one region "
          "high; diffuse = broadly elevated).\n"]
    recs = []
    for i, r in ex.iterrows():
        finding, paragraph, isfoc = m58.build(r, stage_map.get(r.eeg_id, {}))
        recs.append(dict(eeg_id=r.eeg_id, isfoc=bool(isfoc), domstage=str(r.domstage), peakz=float(r.peakz),
                         age=float(r.age) if np.isfinite(r.age) else np.nan, sex=str(r.sex),
                         finding=finding, paragraph=paragraph, report_struct=report_structured(r)))
        kind = "Focal" if isfoc else "Generalized"
        age = int(r.age) if np.isfinite(r.age) else "?"; sex = str(r.sex)[:1].upper() if isinstance(r.sex, str) else "?"
        cent = m58.centile_word(r.peakz)
        header = f"{kind} slowing · peak {r.peakz:.1f} SD ({cent} centile) · prominent in {r.domstage} · {age}{sex}"
        rep = report_structured(r)
        # regional strip
        axb = fig.add_subplot(gs[i, 0])
        vals = [float(getattr(r, c)) if np.isfinite(getattr(r, c, np.nan)) else 0.0 for c in REGN]
        colors = ["#c8443c" if v > 1.0 else "#e0a0a0" if v > 0 else "#bbb" for v in vals]
        axb.barh(range(len(vals))[::-1], vals, color=colors)
        axb.axvline(0, color="#666", lw=.6); axb.set_yticks(range(len(vals))[::-1]); axb.set_yticklabels(REGL, fontsize=7)
        axb.set_xlim(min(-0.5, min(vals) - 0.2), max(3.0, max(vals) + 0.2)); axb.set_xlabel("δ-excess z", fontsize=7)
        axb.tick_params(labelsize=7); axb.set_title("regional deviation", fontsize=7.5)
        # text — step y by wrapped-line count so blocks never overlap
        axt = fig.add_subplot(gs[i, 1]); axt.axis("off")
        axt.add_patch(FancyBboxPatch((0, 0), 1, 1, boxstyle="round,pad=0.01", transform=axt.transAxes,
                                     fc="#f6f7f8", ec="#d0d4d8", lw=.8, zorder=-1))
        y = [0.955]; LH = 0.058

        def emit(text, color, bold=False, wrapw=104, gap=0.02):
            for ln in (textwrap.wrap(text, wrapw) or [""]):
                axt.text(0.015, y[0], ln, fontsize=8.4, color=color, fontweight=("bold" if bold else "normal"),
                         va="top", transform=axt.transAxes)
                y[0] -= LH
            y[0] -= gap
        emit(f"Case {i+1}.   {header}", "#111", bold=True)
        emit("Ours (brief): " + finding, "#127a3d")
        emit("Ours (full): " + paragraph, "#12608a")
        emit("Report (structured): " + rep, "#a5561f")
        md.append(f"**Case {i+1} — {header}**  \n- Ours (brief): {finding}  \n- Ours (full): {paragraph}  \n- Report (structured): {rep}\n")
    fig.suptitle("Example automated slowing reports vs the clinical report — focal & generalized, varying degree & sleep stage",
                 fontsize=12, y=0.995)
    fig.savefig(FIG / "s4_examples_panel.png", dpi=150, bbox_inches="tight"); plt.close(fig)
    pd.DataFrame(recs).to_parquet(RES / "s4_examples.parquet", index=False)   # for scripts/63 (EEG traces)
    (RES / "s4_examples.md").write_text("\n".join(md))
    print(f"chose {n} examples:", [f"{r.eeg_id}({'F' if r.isfoc else 'G'},{r.domstage},{r.peakz:.1f})" for _, r in ex.iterrows()])
    print("wrote figures/story/s4_examples_panel.png + results/story/s4_examples.md")


if __name__ == "__main__":
    main()
