"""Manuscript figure — a panel of 6 example recordings (focal / generalized slowing of varying degree, in
different sleep stages) with (a) our BRIEF finding line, (b) our FULL report paragraph, and (c) the clinical
report for comparison — shown as its STRUCTURED descriptors (raw report text is PHI and is never rendered).

Each card also shows a compact regional delta-excess deviation strip (6 regions) that visually distinguishes
focal (one region high) from diffuse (all elevated). Reports are generated by the SAME governed generator
used in §4 D6 (scripts/58). Reuses description_recording/description_stage + recording_labels(_sap) +
recording_meta (age/sex).

Run: PYTHONPATH=src MPLBACKEND=Agg python3 scripts/62_example_reports_panel.py
Writes figures/story/s4_examples_panel.png + results/story/s4_examples.md
"""
from __future__ import annotations
import importlib.util, textwrap, re
from pathlib import Path
import numpy as np, pandas as pd
import matplotlib; matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch

MANIFEST = "data/manifest/report_manifest_v6.parquet"
# Recordings never used as figure examples. S0001121298232 is a burst-suppression study mis-staged as REM —
# its report ("burst suppression with bursts of irregular theta slowing") is not a clean generalized-slowing
# case, so it makes a misleading LENS-vs-report comparison.
EXCLUDE_IDS = ("S0001121298232",)

# The six recordings shown in Figures 4 and 5, PINNED.
#
# Why pin rather than re-search: the search ranks candidates on `peak_region`/`peak_region_z`, and the
# normative grid gained four regions during the revision (7 -> 11: L/R anterior and L/R posterior, the split
# SS2 describes, 210 -> 330 cells). That legitimately re-ranks the focal pool, so re-running picked three
# DIFFERENT focal patients than the figures the reviewers read and commented on panel-by-panel.
#
# Changing which patients appear mid-revision would orphan those comments for no scientific gain -- the cases
# are illustrations, not results. So the identities are fixed here and only their CARDS are recomputed, which
# is what actually needed updating: the committed cards were built from the superseded 7-region descriptors.
# Order is the display order: 3 focal (marked/moderate/mild), then 3 generalized.
PINNED_EXAMPLES = (
    "S0001116080658_20120620112030",   # focal, marked. Chosen deliberately, not by the search: its
                                       # impression reads "high amplitude continuous FOCAL delta slowing
                                       # over the left hemisphere, maximal over the left anterior temporal
                                       # region. there were no epileptiform..." -- focal-first rather than
                                       # diffuse-with-a-superimposed-focus, which is what this figure is
                                       # for. Ranked on FOCALITY (peak region z minus the median region),
                                       # not peak z alone: the highest-z recordings are diffusely slow with
                                       # a focus riding on top, so LENS describes them as diffuse and the
                                       # panel then contradicts the figure it sits in. Left-sided, which
                                       # also contrasts with the right temporal panel beside it. The automatic pick is not trustworthy here --
                                       # de-identification redacts findings behind asterisks, so a text
                                       # screen cannot see "abundant ****** sharp discharges", and ranking on
                                       # peak z alone surfaced an attenuation case and a status-epilepticus
                                       # case. Replaces S0001112857553_20160206081631, whose impression
                                       # (S0001112857553_20160206081631) has "abundant spike and slow wave
                                       # discharges" as the first item of its impression, so its displayed
                                       # segment is epileptiform rather than the focal slowing the figure
                                       # claims to show. Re-picked under the widened screen above.
    "S0001120133802_20120917122010",   # focal, moderate
    "S0002118633403_20191203074129",   # focal, mild
    "S0001119160767_20190930133101",   # generalized, marked
    "S0002114400117_20220102134116",   # generalized, moderate
    "S0002119199989_20170830132221",   # generalized, mild
)
# Pull ONLY the SLOWING-finding sentence(s) from the clinical report: require the core word "slow", and drop
# sentences about medications / history / times / epileptiform activity — those are off-topic for this figure
# and the most PHI-sensitive part. Then de-identify (dates, times, redaction stars, long-number IDs, names).
SLOW_KW = re.compile(r"\bslow(ing|ed|s)?\b", re.I)
# a recording is NOT a clean "slowing" exemplar if its report describes a PERIODIC/rhythmic epileptiform pattern
# (LPDs/PLEDs/GPDs/triphasic/LRDA) — those are ictal-interictal-continuum patterns, not background slowing, and
# would dominate the displayed segment. (Narrow on purpose: 84% of reports mention some spike/discharge term.)
PERIODIC = re.compile(r"\b(lpd|pled|lrda|periodic|triphasic|gpd|bipd)s?\b", re.I)
# 22cad20 excluded PERIODIC exemplars after a reviewer noted a focal example was LPDs rather than slowing.
# That filter was too narrow: it names periodic patterns only, so a report whose impression reads "1) abundant
# spike and slow wave discharges in the right posterior quadrant 2) focal slowing in the right posterior"
# passed it, and that recording became Figure 4's marked focal panel -- a figure illustrating focal SLOWING
# whose displayed segment is substantially epileptiform, in the same region.
EPILEPTIFORM = re.compile(r"\b(spike|sharp wave|sharp-wave|polyspike|epileptiform|electrographic seizure)s?\b",
                          re.I)
# ... but the mention must be ASSERTED. "there are no definite epileptiform abnormalities" is a clean report
# and a legitimate exemplar, so a bare keyword search would throw away good cases along with bad ones.
_NEG = re.compile(r"\b(no|not|none|without|absent|negative for|free of|unremarkable)\b", re.I)


def _asserts(pat, s: str) -> bool:
    """True if `pat` matches a clause of `s` that is not negated."""
    for clause in re.split(r"[.;\n]|\d\)", str(s or "")):
        if pat.search(clause) and not _NEG.search(clause):
            return True
    return False


def asserts_epileptiform(impression: str) -> bool:
    """True if the IMPRESSION asserts epileptiform activity (not merely mentions or negates it).

    Scoped to the impression on purpose: the full report also carries indication, history and comparison to
    prior studies, which mention epileptiform activity that is not in this recording at all.
    """
    for clause in re.split(r"[.;\n]|\d\)", str(impression or "")):
        if (EPILEPTIFORM.search(clause) or PERIODIC.search(clause)) and not _NEG.search(clause):
            return True
    return False
EXCLUDE = re.compile(r"\b(medication|treatment|administered|history|reason for|hemorrhage|h/o|epoch|start:|end:|"
                     r"comparison|clinical correlation|discharge|spike|seizure|anti-?seizure|dose|mg|bid|q\d+h|"
                     r"propofol|clobazam|lamotrigine|phenobarbital|phenytoin|lacosamide|keppra|levetiracetam)\b", re.I)
# leading report boilerplate to strip so a snippet never reads "Report impression: final report impression: ..."
BOILER = re.compile(r"^\s*(\*+\s*final report\s*\*+|final report impression|final impression|summary impression|"
                    r"final correlation|clinical correlation|final report|impression|report)\s*[:\-.]*\s*", re.I)


def _strip_boiler(s: str) -> str:
    prev = None
    while s and s != prev:                            # repeat: handles "final report impression: impression: ..."
        prev = s; s = BOILER.sub("", s).strip()
    return s


def _scrub(s: str) -> str:
    s = re.sub(r"\b\d{1,2}[/-]\d{1,2}[/-]\d{2,4}\b|\b\d{4}-\d{2}-\d{2}\b|\b\d{1,2}:\d{2}(:\d{2})?\b", "[…]", s)  # dates/times
    s = re.sub(r"\*+", "", s)                                                              # redaction stars
    s = re.sub(r"\b\d{5,}\b", "[id]", s)
    s = re.sub(r"\b(Dr\.?|Drs\.?|MD|M\.D\.)\s+[A-Z][a-z]+", "[physician]", s)
    return _strip_boiler(re.sub(r"\s+", " ", s).strip().strip(":").strip())


def _slow_sentences(text):
    if not isinstance(text, str) or not text.strip():
        return []
    return [s for s in re.split(r"(?<=[.!?])\s+", text.replace("\n", " "))
            if SLOW_KW.search(s) and not EXCLUDE.search(s)]


def _clip(out, maxchar):
    return out[:maxchar].rsplit(" ", 1)[0] + "…" if len(out) > maxchar else out


def slowing_snippet(text, maxn=2, maxchar=300) -> str:
    return _clip(_scrub(" ".join(_slow_sentences(text)[:maxn])), maxchar)


def _norm(s):                                          # normalized 60-char prefix key (robust to truncation)
    return re.sub(r"[^a-z0-9]+", " ", _strip_boiler(s).lower()).strip()[:60]


def detail_snippet(text, impression, maxn=3, maxchar=340) -> str:
    """Detailed description = slowing sentences the impression does NOT already state; a note when it adds none."""
    imp = {_norm(s) for s in re.split(r"(?<=[.!?])\s+", impression or "") if s.strip()}
    extra = [s for s in _slow_sentences(text) if _norm(s) not in imp][:maxn]
    out = _clip(_scrub(" ".join(extra)), maxchar)
    return out or "— the report gives no detailed description beyond the impression above"


def _consistent(field, body) -> bool:
    """True if the impression FIELD lines up with a body sentence (guards against truncated impression fields,
    e.g. a stored 'normal eeg...' where the body correctly reads 'abnormal eeg...')."""
    fk = _norm(field)[:25]
    if not fk:
        return False
    return any((sk := _norm(s)[:25]).startswith(fk) or fk.startswith(sk) for s in _slow_sentences(body))


def report_two_part(imp_raw, det_raw):
    """(impression, detail) for a Figure-4 card: the concise impression FIELD when it is consistent with the full
    report body, else the body's lead slowing sentence; detail = the body sentences beyond the impression."""
    imp_field = slowing_snippet(imp_raw, maxn=2)
    impression = imp_field if _consistent(imp_field, det_raw) else slowing_snippet(det_raw, maxn=1)
    return impression, detail_snippet(det_raw, impression)


# Author-curated (impression, description) for the six figure exemplars. The automated split above only works
# when the report carries a separate impression field, which is absent in ~56% of notes (report_impression is
# populated 44%); when it is missing the extractor takes the body's FIRST slowing sentence as the "impression",
# but reports are written description-first / conclusion-last, so the true impression sinks into the detail slot.
# These six were hand-selected from the de-identified reports (impression = the report's conclusion; description =
# the descriptive body) to make the two-way LENS↔report comparison faithful. Text is verbatim from the reports
# (already de-identified; committable per project policy); "…" marks author-elided intervening text.
REPORT_OVERRIDES = {
    "S0001112857553_20160206081631": (
        "focal slowing in the right posterior region",
        "on the right, there is near continuous 3-5 hz of focal slowing in the posterior quadrant…drowsiness was "
        "characterized by generalized background slowing and gradual dropout of the posterior dominant rhythm. "
        "stage ii sleep was seen, characterized by sleep spindles."),
    "S0001120133802_20120917122010": (
        "focal right fronto-temporal theta slowing",
        "there was increased slowing over the right frontotemporal region. during drowsiness and sleep, "
        "generalized slowing, vertex sharp waves, sleep spindles and k-complexes were recorded."),
    "S0002118633403_20191203074129": (
        "left hemisphere slowing",
        "over the left hemisphere, there is moderate amplitude left temporo-parietal delta/theta slowing which "
        "rarely form fluctuating semi-rhythmic activity…intermittent drowsiness is characterized by attenuation of "
        "the background, slow roving eye movements and bilateral slowing in the theta and delta range, l>>r."),
    "S0001119160767_20190930133101": (
        "occasional periods of generalized delta slowing alternating with periods of lower voltage theta slowing "
        "of the background.",
        "there is frequent 3-5 hz generalized slowing in the 60-100 uv range"),
    "S0002114400117_20220102134116": (
        "disorganized diffusely slow background",
        "the background is disorganized with no clear discernible posterior rhythm, but rather predominantly "
        "20-40 v, theta and delta slowing."),
    "S0002119199989_20170830132221": (
        "abnormal, due to frequent bilateral anterior slowing, as well as bilateral high voltage theta bursts",
        "there is frequent bifrontal slowing with mostly theta activity. there are also independent bursts of "
        "bilateral high voltage theta without any reported symptoms. drowsiness is characterized by attenuation of "
        "the background rhythm, bilateral slowing. all stages of sleep are seen without major abnormalities in "
        "morphology."),
}


def curated_two_part(eid, imp_raw, det_raw):
    """Author-curated (impression, description) when available, else the automated split."""
    return REPORT_OVERRIDES.get(eid) or report_two_part(imp_raw, det_raw)

m58 = importlib.util.module_from_spec(importlib.util.spec_from_file_location("m58", "scripts/58_description_words.py"))
importlib.util.spec_from_file_location("m58", "scripts/58_description_words.py").loader.exec_module(m58)

FIG = Path("figures/story"); RES = Path("results/story")
REGN = ["reg_anterior", "reg_L_temporal", "reg_R_temporal", "reg_L_parasagittal", "reg_R_parasagittal", "reg_posterior"]
REGL = ["ant", "L-temp", "R-temp", "L-para", "R-para", "post"]
STAGES = ["W", "N1", "N2", "N3", "REM"]


def report_structured(r):
    """PHI-free stand-in for the clinical report: its structured finding labels."""
    parts = []
    if bool(getattr(r, "slowing_focal", False)):
        loc = " ".join(x for x in [str(getattr(r, "focal_side", "") or ""), str(getattr(r, "focal_region", "") or "")] if x and x != "nan")
        b = str(getattr(r, "focal_band", "") or ""); b = "" if b == "nan" else b
        parts.append("focal slowing" + (f", {loc}" if loc.strip() else "") + (f" ({b})" if b else ""))
    if bool(getattr(r, "slowing_gen_pathologic", False)):
        topo = str(getattr(r, "gen_topography", "") or ""); topo = "" if topo in ("nan", "unspec") else topo
        b = str(getattr(r, "gen_band", "") or ""); b = "" if b == "nan" else b
        parts.append("generalized slowing" + (f", {topo}" if topo else "") + (f" ({b})" if b else ""))
    return "; ".join(parts) if parts else "slowing (unspecified)"


def main():
    FIG.mkdir(parents=True, exist_ok=True); RES.mkdir(parents=True, exist_ok=True)
    R = pd.read_parquet("data/derived/description_recording.parquet")
    S = pd.read_parquet("data/derived/description_stage.parquet")
    lab = pd.read_parquet("data/derived/recording_labels.parquet").drop_duplicates("eeg_id")
    sap = pd.read_parquet("data/derived/recording_labels_sap.parquet").drop_duplicates("eeg_id")
    meta = pd.read_parquet("data/derived/recording_meta.parquet").drop_duplicates("eeg_id").set_index("eeg_id")
    man = pd.read_parquet(MANIFEST).drop_duplicates("eeg_id").set_index("eeg_id")   # clinical report text (impression + detail)
    d = R.merge(lab[["eeg_id", "focal_side", "focal_region", "focal_band", "gen_band", "gen_topography"]], on="eeg_id") \
         .merge(sap[["eeg_id", "slowing_focal", "slowing_gen_pathologic"]], on="eeg_id")
    d = d[d.slowing_focal.fillna(False) | d.slowing_gen_pathologic.fillna(False)].copy()
    d = d[~d.eeg_id.astype(str).str.startswith(EXCLUDE_IDS)].copy()             # drop known-bad example recordings
    S = S[S.eeg_id.isin(set(d.eeg_id))].copy(); S["amount"] = S[["delta_p90", "theta_p90"]].max(axis=1)
    stage_map = {eid: {r.stage: (r.prevalence, r.n_seg, r.amount) for r in g.itertuples()} for eid, g in S.groupby("eeg_id")}
    d["isfoc"] = d.apply(m58.ourisfoc, axis=1)
    d["gen"] = d.apply(m58.has_generalized, axis=1)
    d["peakz"] = [m58.magnitude(r, r.isfoc) for r in d.itertuples()]
    d["domstage"] = d.eeg_id.map(lambda e: max(stage_map.get(e, {"W": (0, 0, -9)}), key=lambda s: stage_map[e][s][2]) if stage_map.get(e) else "W")
    d["age"] = d.eeg_id.map(meta.age); d["sex"] = d.eeg_id.map(meta.sex)
    d["our_side"] = [m58.our_side(v) for v in d.lat_signed]
    d["concord"] = (d.our_side == d.focal_side) | (d.focal_side.isna())            # side agrees (or n/a for gen)
    d = d[d.peakz.notna() & d.age.notna() & (d.n_seg >= 20)]

    # keep only recordings whose report yields BOTH a brief impression AND a distinct detailed description, so
    # every Figure-4 card shows a real two-way comparison and never falls back to a "no detail" note
    def _two_part(eid):
        if eid in REPORT_OVERRIDES:
            return True                                                            # author-curated -> always valid
        if eid not in man.index:
            return False
        impr, det = report_two_part(man.report_impression.get(eid, ""), man.report_text.get(eid, ""))
        return bool(impr) and not det.startswith("—")
    d = d[d.eeg_id.map(_two_part)]

    # drop recordings whose report describes a PERIODIC epileptiform pattern (LPDs etc.) — not clean slowing
    def _no_periodic(eid):
        """Reject only recordings whose report ASSERTS a periodic or epileptiform pattern.

        The original screen matched PERIODIC anywhere in impression+text with no negation handling, so a
        structured report reading "periodic or rhythmic patterns: none. epileptiform discharges: none."
        was rejected for containing the word "periodic" -- it silently discarded exactly the cleanest
        candidates, the ones whose reports state the absence explicitly.
        """
        if eid not in man.index:
            return True
        imp = str(man.report_impression.get(eid, "") or "")
        txt = str(man.report_text.get(eid, "") or "")
        # The IMPRESSION decides what this recording's primary abnormalities are, so epileptiform content
        # there disqualifies it. The body text also carries indication, history and prior-study comparison,
        # where an epileptiform mention says nothing about this recording -- scanning it for epileptiform
        # rejected good exemplars. It is still scanned for PERIODIC patterns, because that was the original
        # concern (an LPD run visible in the displayed segment), now negation-aware so a report stating
        # "periodic or rhythmic patterns: none" is kept.
        return not (asserts_epileptiform(imp) or _asserts(PERIODIC, txt))
    d = d[d.eeg_id.map(_no_periodic)]

    # --- pick 6 CONCORDANT examples (our field agrees slowing is present), 3 focal + 3 generalized,
    #     spanning degree (marked/moderate/mild) and DIFFERENT dominant sleep stages ---
    def pick(pool, used_ids, used_stages, used_regions, band):
        lo, hi = band
        p = pool[(pool.peakz >= lo) & (pool.peakz < hi) & (~pool.eeg_id.isin(used_ids))]
        if not len(p):                                                                # relax band if empty
            p = pool[(pool.peakz >= 1.0) & (~pool.eeg_id.isin(used_ids))]
        if not len(p):
            return None
        pu = p[~p.domstage.isin(used_stages)]                                          # prefer an unused stage
        p = pu if len(pu) else p
        if "peak_region" in p.columns:                                                # prefer an unused region (variety)
            pr = p[~p.peak_region.isin(used_regions)]; p = pr if len(pr) else p
        pc = p[p.concord]                                                              # prefer report-concordant side
        p = pc if len(pc) else p
        return p.sort_values("n_seg", ascending=False).iloc[0]
    # EXCLUSIVELY focal / generalized (report AND model agree) so each example shows one clean pattern.
    # Focal cases additionally require a CLEARLY lateralized field (|lat_signed| >= LAT_MIN): a weak asymmetry
    # gives an unreliable side/electrode call that the displayed segment can contradict (QC catch 2026-07-19).
    LAT_MIN = 1.5
    foc = d[d.isfoc & (~d.gen) & (d.slowing_focal == True) & (d.slowing_gen_pathologic != True)
            & d.focal_side.notna() & (d.lat_signed.abs() >= LAT_MIN)]                                               # noqa: E712
    gen = d[(~d.isfoc) & d.gen & (d.slowing_gen_pathologic == True) & (d.slowing_focal != True)]                    # noqa: E712
    MARKED, MODERATE, MILD = (3.0, 12.0), (1.8, 3.0), (1.0, 1.8)
    chosen = []
    # iterrows, not itertuples: pick() returns a Series, and pd.DataFrame() cannot build a frame from a
    # mix of namedtuples and Series once a reopened slot puts both in `chosen`.
    by_id = {str(r.eeg_id): r for _, r in d.iterrows()}
    # A pin of None reopens that slot: the identity is filled by the ordinary search while every other
    # panel keeps the recording the reviewers saw. A pinned id that has DISAPPEARED is a different matter
    # and still triggers the loud fallback below.
    missing = [e for e in PINNED_EXAMPLES if e is not None and e not in by_id]
    if not missing:
        # Seed the "already used" sets from the PINNED rows first. Without this a reopened slot is filled
        # before the picker knows which stages and regions the pinned panels occupy, so it can duplicate
        # them -- reopening the marked-focal slot produced a second REM panel beside the pinned REM one.
        used_ids = set(e for e in PINNED_EXAMPLES if e)
        used_stages = [by_id[e].domstage for e in PINNED_EXAMPLES if e and e in by_id]
        used_regions = set(by_id[e].peak_region for e in PINNED_EXAMPLES
                           if e and e in by_id and pd.notna(by_id[e].peak_region))
        for slot, (pool, band) in zip(PINNED_EXAMPLES,
                                      [(foc, MARKED), (foc, MODERATE), (foc, MILD),
                                       (gen, MARKED), (gen, MODERATE), (gen, MILD)]):
            if slot is not None:
                chosen.append(by_id[slot]); continue
            r = pick(pool, used_ids, used_stages, used_regions, band)
            if r is not None:
                used_ids.add(r.eeg_id); used_stages.append(r.domstage)
                used_regions.add(r.peak_region); chosen.append(r)
                print(f"  reopened slot filled with {r.eeg_id} ({r.peakz:.1f} SD, {r.domstage})")
    else:
        # Only reachable if the pinned recordings drop out of the descriptor table entirely. Say so loudly
        # rather than silently swapping in different patients, which is exactly the failure this pin exists
        # to prevent.
        print(f"WARNING: {len(missing)} pinned example(s) absent from description_recording "
              f"({missing}); falling back to the automatic search, so Figures 4/5 will show DIFFERENT "
              f"patients than the reviewed version.")
        used_ids, used_stages, used_regions = set(), [], set()
        for pool, band in [(foc, MARKED), (foc, MODERATE), (foc, MILD),
                           (gen, MARKED), (gen, MODERATE), (gen, MILD)]:
            r = pick(pool, used_ids, used_stages, used_regions, band)
            if r is not None:
                used_ids.add(r.eeg_id); used_stages.append(r.domstage)
                used_regions.add(r.peak_region); chosen.append(r)
    ex = pd.DataFrame(chosen).reset_index(drop=True)

    # --- render 6 cards (one row each) ---
    n = len(ex); fig = plt.figure(figsize=(12.5, 3.0 * n + 0.5))
    gs = fig.add_gridspec(n, 2, width_ratios=[1, 4.0], hspace=0.55, wspace=0.06)
    md = ["# Example generated reports vs the clinical report (6 recordings)\n",
          "LENS's BRIEF finding line and FULL report paragraph (governed by docs/claims_table.md — magnitude in "
          "SD/centile, no severity adjective) beside the clinical report's STRUCTURED descriptors (raw report "
          "text withheld as PHI). Regional strip = per-region delta-excess deviation z (focal = one region "
          "high; diffuse = broadly elevated).\n"]
    recs = []
    for i, r in ex.iterrows():
        finding, paragraph, isfoc = m58.build(r, stage_map.get(r.eeg_id, {}))
        imp = man.report_impression.get(r.eeg_id, "") if r.eeg_id in man.index else ""
        det = man.report_text.get(r.eeg_id, "") if r.eeg_id in man.index else ""
        report_impression_text, report_detail_text = curated_two_part(r.eeg_id, imp, det)
        recs.append(dict(eeg_id=r.eeg_id, isfoc=bool(isfoc), domstage=str(r.domstage), peakz=float(r.peakz),
                         age=float(r.age) if np.isfinite(r.age) else np.nan, sex=str(r.sex),
                         # the claimed focal region (maps to a segment_deviation region) so Figure 4 can display
                         # the segment where THIS region peaks, not just the max whole-head-amount segment
                         peak_region=(str(r.peak_region) if isfoc and pd.notna(r.get("peak_region")) else None),
                         finding=finding, paragraph=paragraph, report_struct=report_structured(r),
                         report_impression_text=report_impression_text, report_detail_text=report_detail_text))
        kind = "Focal" if isfoc else "Generalized"
        age = int(r.age) if np.isfinite(r.age) else "?"; sex = str(r.sex)[:1].upper() if isinstance(r.sex, str) else "?"
        cent = m58.centile_word(r.peakz)
        header = f"{kind} slowing · peak {r.peakz:.1f} SD ({cent} centile) · prominent in {r.domstage} · {age}{sex}"
        rep = report_structured(r)
        # regional strip
        axb = fig.add_subplot(gs[i, 0])
        vals = [float(getattr(r, c)) if np.isfinite(getattr(r, c, np.nan)) else 0.0 for c in REGN]
        colors = ["#c8443c" if v > 1.0 else "#e0a0a0" if v > 0 else "#bbb" for v in vals]
        axb.barh(range(len(vals))[::-1], vals, color=colors)
        axb.axvline(0, color="#666", lw=.6); axb.set_yticks(range(len(vals))[::-1]); axb.set_yticklabels(REGL, fontsize=7)
        axb.set_xlim(min(-0.5, min(vals) - 0.2), max(3.0, max(vals) + 0.2)); axb.set_xlabel("δ-excess z", fontsize=7)
        axb.tick_params(labelsize=7); axb.set_title("regional deviation", fontsize=7.5)
        # text — step y by wrapped-line count so blocks never overlap
        axt = fig.add_subplot(gs[i, 1]); axt.axis("off")
        axt.add_patch(FancyBboxPatch((0, 0), 1, 1, boxstyle="round,pad=0.01", transform=axt.transAxes,
                                     fc="#f6f7f8", ec="#d0d4d8", lw=.8, zorder=-1))
        y = [0.955]; LH = 0.058

        def emit(text, color, bold=False, wrapw=104, gap=0.02):
            for ln in (textwrap.wrap(text, wrapw) or [""]):
                axt.text(0.015, y[0], ln, fontsize=8.4, color=color, fontweight=("bold" if bold else "normal"),
                         va="top", transform=axt.transAxes)
                y[0] -= LH
            y[0] -= gap
        emit(f"Case {i+1}.   {header}", "#111", bold=True)
        emit("LENS (brief): " + finding, "#127a3d")
        emit("LENS (full): " + paragraph, "#12608a")
        emit("Report (structured): " + rep, "#a5561f")
        md.append(f"**Case {i+1} — {header}**  \n- LENS (brief): {finding}  \n- LENS (full): {paragraph}  \n- Report (structured): {rep}\n")
    fig.suptitle("Example automated slowing reports vs the clinical report — focal & generalized, varying degree & sleep stage",
                 fontsize=12, y=0.995)
    fig.savefig(FIG / "s4_examples_panel.png", dpi=300, bbox_inches="tight"); plt.close(fig)
    pd.DataFrame(recs).to_parquet(RES / "s4_examples.parquet", index=False)   # for scripts/63 (EEG traces)
    (RES / "s4_examples.md").write_text("\n".join(md))
    print(f"chose {n} examples:", [f"{r.eeg_id}({'F' if r.isfoc else 'G'},{r.domstage},{r.peakz:.1f})" for _, r in ex.iterrows()])
    print("wrote figures/story/s4_examples_panel.png + results/story/s4_examples.md")


if __name__ == "__main__":
    main()
